language: python
sudo: false
python:
  - "3.8"

install:
  # Setup bikeshed. See https://tabatkins.github.io/bikeshed/#travis-ci
  - pip3 install bikeshed
  - bikeshed update

script:
  - bash ./deploy.sh

env:
  global:
  - ENCRYPTION_LABEL: "206c68591c5c"
  - COMMIT_AUTHOR_EMAIL: "jsbell@chromium.org"
