language: python
sudo: false
python:
  - '3.7'

install:
  # Setup bikeshed. See https://tabatkins.github.io/bikeshed/#install-linux
  - git clone https://github.com/tabatkins/bikeshed.git
  - pip install --editable $PWD/bikeshed
  - bikeshed update

script:
  - bash ./deploy.sh

env:
  global:
  - ENCRYPTION_LABEL: "206c68591c5c"
  - COMMIT_AUTHOR_EMAIL: "jsbell@chromium.org"
